chdavidanto173/Inge

- node_modules/bootstrap/dist/paginas/Busqueda.html
- node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
Html de Busqueda y Enlace de documentos
> HTML NUEVOS

- node_modules/bootstrap/dist/paginas/Busqueda.html
- node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
Validaciones de los campos de texto
> Validaciones

- node_modules/bootstrap/dist/paginas/Busqueda.html
- node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
Se agrego un calendario en enlace de documentos y una tabla para
mostrar los datos de la correspondencia en Busqueda
> Calendario y tabla

- Situn/node-postgres-promises/public/index.html
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/css/style.css
> style ubicado en css boostrap

- Situn/node-postgres-promises/public/index.html
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/css/style.css
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Busqueda.html
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
> Cambio de apariencia

- Situn/node-postgres-promises/public/index.html
> Estandar metodos IC

- Situn/node-postgres-promises/public/index.html
- Situn/node-postgres-promises/public/javascripts/server.js
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
enlace disque que terminado , sy falta lo de bryhan
> Enlace disque que terminada

- Situn/node-postgres-promises/public/index.html
> validar correspondencias

- Situn/node-postgres-promises/public/javascripts/server.js
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
Modificacion en el enlace y en la buqueda de correspondencia por asunto
en el server
> Arreglo Enlace y servers

- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
Ahora busca con el criterio correcto, antes lo hacia sin tomar en cuenta
la letra que se acaba de presionar
> Arreglo en la busqueda

- Situn/node-postgres-promises/public/index.html
- Situn/node-postgres-promises/public/javascripts/server.js
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Busqueda.html
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
> Actualizado

- Situn/node-postgres-promises/public/index.html
- Situn/node-postgres-promises/public/javascripts/server.js
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
Cambio que dijo la profe y validación de no enlazar el mismo documento
> Cambio que dijo la profe y validación de no enlazar el mismo documento

- Situn/node-postgres-promises/public/index.html
- Situn/node-postgres-promises/public/javascripts/server.js
> Con tabla casi lista

- Situn/node-postgres-promises/public/index.html
> Tabla lista FM

- Situn/node-postgres-promises/public/index.html
Scroll ba en la tabla de alarmas
> Scroll bar

- Situn/node-postgres-promises/public/index.html
> Validacion Alarmas

- Estandar de la base SITUN.txt
- Situn/node-postgres-promises/public/javascripts/server.js
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
- Situn/node-postgres-promises/routes/index.js
- script_SITUN.sql
> cambio base

- Situn/node-postgres-promises/public/index.html
- Situn/node-postgres-promises/public/javascripts/server.js
> Cambios recientes

- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Enlace de Documentos.html
Se agregan los metodos que permiten elegir el criterio de busqueda en el
enlace de documentos
> Criterio de busqueda en enlace

- Situn/node-postgres-promises/public/index.html
- Situn/node-postgres-promises/public/javascripts/server.js
Cambios en base de datos e index
> Cambios en base de datos y index

- Situn/node-postgres-promises/public/index.html
Validaciones de campos de Alarmas
Cambios de hilla en el index
Mensaje  a la hora de quitar alarmas
> Validaciones y mensaje de alarmas

- Situn/node-postgres-promises/public/index.html
- Situn/node-postgres-promises/public/javascripts/server.js
- Situn/node-postgres-promises/public/node_modules/bootstrap/dist/paginas/Busqueda.html
> Actualizacion

- Situn/node-postgres-promises/public/index.html
Validacion de alarmas y mensaje de alarmas mas pequeño
> Actualizacion validar alarmas

- Situn/node-postgres-promises/public/index.html
> Validacion de alarmas

- Situn/node-postgres-promises/public/index.html
- Situn/node-postgres-promises/public/javascripts/server.js
> formato fecha base
